FROM docker.io/openjdk:25-jdk-slim

WORKDIR /app

# 复制jar包
COPY openadmin-samples/target/openadmin-samples-10.3.0-SNAPSHOT.jar app.jar

# 暴露端口
EXPOSE 8082

# 启动应用
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.profiles.active=docker"]